import {
  nodeAt,
  sourceLine,
  type MarkdownNode,
  type SourceEdit,
  type TextChange,
} from "@axiom/markdown";
import type { NativeBinding } from "./binding";
import { literalBody } from "./literal";

type Fence = {
  bookmark: ReturnType<NativeBinding["relative"]>;
  from: number;
  body: number;
  close: number;
  to: number;
  opener: string;
  header: string;
  closing: string;
  tail: {
    bookmark: ReturnType<NativeBinding["relative"]>;
    to: number;
    text: string;
  } | null;
};

const closingLine = (source: string, node: MarkdownNode) =>
  sourceLine(source, node.to - (source[node.to - 1] === "\n" ? 2 : 1));

/** Ownership is local to this view, not inferred from Markdown. Only scaffolding
 * just generated by structural Enter can collapse back to its authored opener.
 * Peer edits inside the block and replaced/restored fences revoke ownership.
 * A local language-field edit changes metadata, not ownership of the closer. */
export class GeneratedFences {
  private fences: Fence[] = [];
  constructor(private binding: NativeBinding) {}

  /** Called after a successful Enter, never for paste, import or source loads. */
  remember(before: string, edit: SourceEdit) {
    const change = edit.changes[0];
    if (edit.changes.length !== 1 || !change || change.from !== change.to)
      return;
    const original = sourceLine(before, change.from);
    if (original.to !== change.from || !change.insert.includes("\n")) return;
    const source = this.binding.source;
    const node = nodeAt(source, edit.selection.anchor, [
      "codeBlock",
      "mathBlock",
    ]);
    if (
      !node ||
      literalBody(source, node).text ||
      (node.contentTo ?? node.to) >= node.to
    )
      return;
    const header = sourceLine(source, node.from),
      closing = closingLine(source, node);
    if (
      header.from !== original.from ||
      !header.text.startsWith(original.text) ||
      closing.from <= header.to ||
      closing.from < change.from ||
      closing.to > change.from + change.insert.length
    )
      return;
    this.fences.push({
      bookmark: this.binding.relative({
        anchor: header.from,
        head: closing.to - 1,
      }),
      from: header.from,
      body: header.to,
      close: closing.from,
      to: closing.to,
      opener: original.text,
      header: header.text,
      closing: closing.text,
      tail: {
        bookmark: this.binding.relative({
          anchor: change.from + change.insert.length - 1,
          head: change.from + change.insert.length - 1,
        }),
        to: change.from + change.insert.length,
        text: source.slice(closing.to, change.from + change.insert.length),
      },
    });
    if (this.fences.length > 256) this.fences.shift();
  }

  beforeChange(
    changes: readonly TextChange[],
    remote = false,
    intent?: "code-language",
  ) {
    for (const fence of this.fences) {
      if (
        fence.tail &&
        changes.some(
          (change) => change.from < fence.tail!.to && change.to >= fence.to,
        )
      )
        fence.tail = null;
    }
    this.fences = this.fences.filter((fence) => {
      const header =
        !remote && intent === "code-language"
          ? this.languageHeader(fence, changes)
          : undefined;
      if (header !== undefined) {
        // Prepare the expected header before the synchronous Yjs notification.
        // Keep the original opener so reversal removes later language choices too.
        fence.header = header;
        return true;
      }
      return !changes.some(
        (change) =>
          // Inserting above the block is safe; editing either delimiter is not.
          (change.from < fence.body && change.to > fence.from) ||
          (change.from > fence.from && change.from <= fence.body) ||
          (change.from < fence.to && change.to > fence.close) ||
          (change.from >= fence.close && change.from < fence.to) ||
          (remote && change.from < fence.to && change.to > fence.from),
      );
    });
  }

  private languageHeader(fence: Fence, changes: readonly TextChange[]) {
    const change = changes[0];
    if (
      changes.length !== 1 ||
      !change ||
      !/^[\w+#.-]{0,40}$/.test(change.insert)
    )
      return;
    const source = this.binding.source,
      node = nodeAt(source, fence.body, ["codeBlock"]);
    if (!node || sourceLine(source, node.from).from !== fence.from) return;
    const match = /^([ \t]*(?:`{3,}|~{3,})[ \t]*)([\w+#.-]*)[ \t]*$/.exec(
      source.slice(node.from, fence.body),
    );
    // Only the complete info token may change. Never exempt delimiters,
    // containers, body text, multi-range edits, or a peer's language replacement.
    if (
      !match ||
      change.from !== node.from + match[1].length ||
      change.to !== change.from + match[2].length
    )
      return;
    return (
      source.slice(fence.from, change.from) +
      change.insert +
      source.slice(change.to, fence.body)
    );
  }

  rebase() {
    const source = this.binding.source;
    this.fences = this.fences.filter((fence) => {
      const range = this.binding.absolute(fence.bookmark);
      if (!range || range.anchor >= range.head) return false;
      const header = sourceLine(source, range.anchor),
        closing = sourceLine(source, range.head);
      if (
        header.from !== range.anchor ||
        header.text !== fence.header ||
        closing.to !== range.head + 1 ||
        closing.text !== fence.closing ||
        closing.from <= header.to
      )
        return false;
      fence.from = header.from;
      fence.body = header.to;
      fence.close = closing.from;
      fence.to = closing.to;
      if (fence.tail) {
        const tail = this.binding.absolute(fence.tail.bookmark);
        if (
          !tail ||
          source.slice(fence.to, tail.anchor + 1) !== fence.tail.text
        )
          fence.tail = null;
        else fence.tail.to = tail.anchor + 1;
      }
      return true;
    });
  }

  /** Caller has verified that this body is empty or is being wholly deleted.
   * Remove untouched generated spacing too, unless it separates new following
   * text. Authored/peer-modified separators must never disappear or join text. */
  collapse(node: MarkdownNode): SourceEdit | null {
    this.rebase();
    if (!["codeBlock", "mathBlock"].includes(node.type)) return null;
    const source = this.binding.source;
    const header = sourceLine(source, node.from),
      closing = closingLine(source, node);
    const fence = this.fences.find(
      (f) => f.from === header.from && f.to === closing.to,
    );
    if (!fence) return null;
    let kept = 0;
    while (
      kept < fence.opener.length &&
      fence.opener[kept] === fence.header[kept]
    )
      kept++;
    const from = fence.from + kept;
    const to =
      fence.tail &&
      (fence.tail.to === source.length ||
        /^[\r\n]/.test(source.slice(fence.tail.to)))
        ? fence.tail.to
        : fence.to;
    return {
      changes: [{ from, to, insert: fence.opener.slice(kept) }],
      selection: { anchor: fence.from + fence.opener.length },
    };
  }
}
