/** Original component systems, independent of palette, typography and behavior. */
export const interfaceStyleIds = [
  "axiom",
  "contour",
  "vector",
  "folio",
  "harbor",
  "signal",
  "gridwork",
  "cutline",
] as const;
export type InterfaceStyleId = (typeof interfaceStyleIds)[number];
/** Compatibility only; never offered as new choices. */
export const legacyInterfaceStyleAliases = {
  material: "contour",
  fluent: "vector",
  editorial: "folio",
  macos: "harbor",
} as const satisfies Record<string, InterfaceStyleId>;
export function normalizeInterfaceStyleId(
  value: unknown,
): InterfaceStyleId | undefined {
  if (typeof value !== "string") return undefined;
  if ((interfaceStyleIds as readonly string[]).includes(value))
    return value as InterfaceStyleId;
  return Object.hasOwn(legacyInterfaceStyleAliases, value)
    ? legacyInterfaceStyleAliases[
        value as keyof typeof legacyInterfaceStyleAliases
      ]
    : undefined;
}
export function legacyInterfaceStyleId(
  id: InterfaceStyleId,
  version: number,
): string | undefined {
  if (version >= 12 || id === "axiom") return id;
  if (version === 10 && id === "harbor") return undefined;
  return Object.entries(legacyInterfaceStyleAliases).find(
    ([, current]) => current === id,
  )?.[0];
}
/** Every resolved profile supplies every role. No per-page drawing or remote resources. */
const foundation = {
  "--control-radius": "var(--radius)",
  "--control-radius-small": "calc(var(--radius) * 0.5)",
  "--panel-radius": "calc(var(--radius) * 1.35)",
  "--window-radius": "calc(var(--radius) * 1.8)",
  "--control-surface": "var(--surface)",
  "--control-edge": "var(--line)",
  "--control-hover": "var(--hover)",
  "--control-selected": "var(--accent-bg)",
  "--control-selected-text": "var(--accent)",
  "--action-rule": "none",
  "--primary-surface": "var(--accent)",
  "--primary-text": "var(--on-accent)",
  "--primary-edge": "transparent",
  "--primary-hover": "color-mix(in srgb, var(--accent) 90%, var(--text))",
  "--primary-rule": "none",
  "--icon-surface": "transparent",
  "--icon-edge": "transparent",
  "--field-surface": "var(--surface)",
  "--field-edge": "var(--line)",
  "--field-hover-edge": "var(--muted)",
  "--field-focus-edge": "var(--focus)",
  "--field-border-width": "1px",
  "--field-radius": "var(--control-radius)",
  "--field-rule": "none",
  "--field-adornment-edge": "transparent",
  "--field-adornment-surface": "transparent",
  "--field-focus-rule": "inset 0 0 0 1px var(--focus)",
  "--checkbox-radius": "min(0.25em, calc(var(--radius) * 0.3))",
  "--checkbox-surface": "var(--paper)",
  "--checkbox-selected": "var(--accent)",
  "--checkbox-ink": "var(--on-accent)",
  "--switch-width": "2.6em",
  "--switch-height": "1.5em",
  "--switch-radius": "calc(var(--radius) * 2)",
  "--switch-knob-radius": "50%",
  "--switch-off": "color-mix(in srgb, var(--muted) 18%, var(--paper))",
  "--slider-track-height": "4px",
  "--slider-thumb-width": "16px",
  "--slider-thumb-height": "16px",
  "--slider-thumb-radius": "50%",
  "--slider-thumb-fill": "var(--paper)",
  "--slider-thumb-border": "var(--accent)",
  "--ui-chrome-bg": "var(--sidebar)",
  "--ui-chrome-text": "var(--text)",
  "--ui-chrome-muted": "var(--muted)",
  "--ui-chrome-line": "var(--line)",
  "--ui-chrome-pattern": "none",
  "--ui-chrome-pattern-size": "auto",
  "--ui-chrome-filter": "none",
  "--ui-header-bg": "var(--paper)",
  "--ui-header-text": "var(--text)",
  "--ui-header-muted": "var(--muted)",
  "--ui-panel-rule": "none",
  "--ui-panel-band": "var(--paper)",
  "--ui-nav-bg": "transparent",
  "--ui-nav-selected": "var(--accent-bg)",
  "--ui-nav-ink": "var(--accent)",
  "--ui-nav-rule": "none",
  "--ui-nav-line": "none",
  "--ui-nav-radius": "var(--control-radius)",
  "--ui-tab-selected": "var(--accent-bg)",
  "--ui-tab-rule": "none",
  "--ui-overlay-bg": "var(--paper)",
  "--ui-overlay-edge": "var(--line)",
  "--ui-overlay-rule": "none",
  "--ui-overlay-shadow": "var(--shadow)",
} satisfies Record<`--${string}`, string>;
export const interfaceRecipeTokens = Object.keys(
  foundation,
) as (keyof typeof foundation)[];
export type InterfaceRecipe = Record<keyof typeof foundation, string>;
export type InterfaceStyleDefinition = {
  id: InterfaceStyleId;
  name: string;
  description: string;
  signatures: readonly [string, string, string];
  recipe: Readonly<InterfaceRecipe>;
};
const profile = (values: Partial<InterfaceRecipe>): InterfaceRecipe => ({
  ...foundation,
  ...values,
});
export const interfaceStyles: readonly InterfaceStyleDefinition[] = [
  {
    id: "axiom",
    name: "Axiom",
    description:
      "Quiet scientific surfaces, balanced fields and soft selection",
    signatures: ["balanced-fields", "quiet-navigation", "plain-overlays"],
    recipe: profile({}),
  },
  {
    id: "contour",
    name: "Contour",
    description:
      "Tonal plates, capsule grouping and expressive vertical controls",
    signatures: ["tonal-plates", "capsule-navigation", "vertical-slider"],
    recipe: profile({
      "--control-radius": "calc(var(--radius) * 1.8)",
      "--control-radius-small": "calc(var(--radius) * 1.1)",
      "--panel-radius": "calc(var(--radius) * 1.8)",
      "--window-radius": "calc(var(--radius) * 2)",
      "--control-surface": "var(--accent-bg)",
      "--control-edge": "transparent",
      "--control-hover":
        "color-mix(in srgb, var(--accent-bg) 85%, var(--accent))",
      "--field-surface":
        "color-mix(in srgb, var(--surface) 75%, var(--accent-bg))",
      "--field-edge": "transparent",
      "--field-rule": "inset 0 -2px var(--line)",
      "--checkbox-surface": "var(--accent-bg)",
      "--slider-track-height": "6px",
      "--slider-thumb-width": "6px",
      "--slider-thumb-height": "22px",
      "--slider-thumb-radius": "var(--control-radius-small)",
      "--slider-thumb-fill": "var(--accent)",
      "--ui-chrome-bg":
        "color-mix(in srgb, var(--sidebar) 70%, var(--accent-bg))",
      "--ui-panel-band": "var(--accent-bg)",
      "--ui-nav-radius": "calc(var(--radius) * 2)",
      "--ui-nav-rule": "inset 0 0 0 1px var(--accent)",
      "--ui-tab-rule": "inset 0 0 0 1px var(--accent)",
      "--ui-overlay-bg": "color-mix(in srgb, var(--paper) 85%, var(--surface))",
    }),
  },
  {
    id: "vector",
    name: "Vector",
    description:
      "Architectural rails, framed fields and precision edge selection",
    signatures: [
      "double-field-rules",
      "edge-rail-navigation",
      "architectural-bands",
    ],
    recipe: profile({
      "--control-radius": "calc(var(--radius) * 0.35)",
      "--control-radius-small": "calc(var(--radius) * 0.25)",
      "--panel-radius": "calc(var(--radius) * 0.65)",
      "--window-radius": "calc(var(--radius) * 0.75)",
      "--control-surface": "var(--paper)",
      "--control-edge": "var(--muted)",
      "--action-rule": "inset 0 -2px var(--line)",
      "--primary-edge": "var(--text)",
      "--primary-rule":
        "inset 0 -3px color-mix(in srgb, var(--on-accent) 40%, transparent)",
      "--field-surface": "var(--paper)",
      "--field-edge": "var(--muted)",
      "--field-rule": "inset 0 -3px var(--line)",
      "--field-adornment-edge": "var(--line)",
      "--checkbox-radius": "min(0.15em, calc(var(--radius) * 0.15))",
      "--switch-radius": "var(--control-radius)",
      "--switch-knob-radius": "var(--control-radius-small)",
      "--slider-track-height": "2px",
      "--slider-thumb-width": "12px",
      "--slider-thumb-height": "18px",
      "--slider-thumb-radius": "var(--control-radius-small)",
      "--ui-panel-rule": "inset 0 3px var(--line)",
      "--ui-panel-band": "var(--surface)",
      "--ui-nav-selected": "var(--surface)",
      "--ui-nav-rule": "inset 3px 0 var(--accent)",
      "--ui-tab-selected": "transparent",
      "--ui-tab-rule": "inset 0 -3px var(--accent)",
      "--ui-overlay-edge": "var(--muted)",
      "--ui-overlay-rule": "inset 0 3px var(--accent)",
    }),
  },
  {
    id: "folio",
    name: "Folio",
    description:
      "Continuous paper, straight ruled fields and editorial underlines",
    signatures: ["ruled-fields", "underline-navigation", "paper-overlays"],
    recipe: profile({
      "--control-radius": "calc(var(--radius) * 0.15)",
      "--control-radius-small": "calc(var(--radius) * 0.1)",
      "--panel-radius": "calc(var(--radius) * 0.25)",
      "--window-radius": "calc(var(--radius) * 0.25)",
      "--control-surface": "transparent",
      "--control-edge": "transparent",
      "--action-rule": "inset 0 -1px var(--muted)",
      "--control-selected": "transparent",
      "--field-surface": "var(--paper)",
      "--field-edge": "transparent",
      "--field-hover-edge": "transparent",
      "--field-focus-edge": "transparent",
      "--field-rule": "inset 0 -1px var(--muted)",
      "--field-radius": "0",
      "--field-focus-rule": "inset 0 -2px var(--focus)",
      "--checkbox-radius": "0",
      "--checkbox-selected": "var(--paper)",
      "--checkbox-ink": "var(--accent)",
      "--switch-radius": "var(--control-radius-small)",
      "--switch-knob-radius": "var(--control-radius-small)",
      "--slider-track-height": "2px",
      "--slider-thumb-width": "5px",
      "--slider-thumb-height": "18px",
      "--slider-thumb-radius": "0",
      "--slider-thumb-fill": "var(--accent)",
      "--ui-chrome-bg": "var(--paper)",
      "--ui-chrome-line": "var(--muted)",
      "--ui-panel-rule": "inset 0 1px var(--line)",
      "--ui-nav-selected": "transparent",
      "--ui-nav-line": "underline",
      "--ui-nav-radius": "0",
      "--ui-tab-selected": "transparent",
      "--ui-tab-rule": "inset 0 -1px var(--accent)",
      "--ui-overlay-shadow": "none",
      "--ui-overlay-edge": "var(--muted)",
      "--ui-overlay-rule": "inset 0 3px var(--line)",
    }),
  },
  {
    id: "harbor",
    name: "Harbor",
    description:
      "Banded desktop chrome, recessed fields and segmented selection",
    signatures: ["recessed-fields", "segmented-navigation", "banded-overlays"],
    recipe: profile({
      "--control-radius": "calc(var(--radius) * 0.65)",
      "--control-radius-small": "calc(var(--radius) * 0.45)",
      "--window-radius": "calc(var(--radius) * 1.6)",
      "--control-surface":
        "color-mix(in srgb, var(--paper) 70%, var(--surface))",
      "--action-rule": "inset 0 1px var(--paper)",
      "--field-surface": "color-mix(in srgb, var(--surface) 70%, var(--paper))",
      "--field-rule": "inset 0 2px var(--line)",
      "--field-adornment-surface": "var(--surface)",
      "--field-adornment-edge": "var(--line)",
      "--switch-width": "2.4em",
      "--switch-height": "1.4em",
      "--slider-track-height": "3px",
      "--slider-thumb-width": "17px",
      "--slider-thumb-height": "17px",
      "--ui-chrome-bg": "var(--chrome-background)",
      "--ui-chrome-filter": "var(--material-filter)",
      "--ui-header-bg": "var(--surface)",
      "--ui-panel-band": "var(--surface)",
      "--ui-panel-rule": "inset 0 1px var(--paper)",
      "--ui-nav-rule": "inset 0 0 0 1px var(--line)",
      "--ui-tab-rule": "inset 0 0 0 1px var(--line)",
      "--ui-overlay-rule": "inset 0 1px var(--paper)",
    }),
  },
  {
    id: "signal",
    name: "Signal",
    description:
      "Contrasting shell bands and compartmented instrument controls",
    signatures: [
      "compartment-fields",
      "inverse-navigation",
      "outlined-actions",
    ],
    recipe: profile({
      "--control-radius": "calc(var(--radius) * 0.4)",
      "--control-radius-small": "calc(var(--radius) * 0.2)",
      "--window-radius": "calc(var(--radius) * 0.6)",
      "--control-edge": "var(--text)",
      "--icon-edge": "var(--line)",
      "--icon-surface": "var(--paper)",
      "--action-rule": "inset 0 0 0 1px var(--text)",
      "--field-surface": "var(--paper)",
      "--field-edge": "var(--text)",
      "--field-adornment-surface": "var(--accent-bg)",
      "--field-adornment-edge": "var(--text)",
      "--field-rule": "inset 3px 0 var(--accent)",
      "--checkbox-radius": "0",
      "--switch-radius": "var(--control-radius-small)",
      "--switch-knob-radius": "var(--control-radius-small)",
      "--slider-track-height": "5px",
      "--slider-thumb-width": "8px",
      "--slider-thumb-height": "20px",
      "--slider-thumb-radius": "0",
      "--slider-thumb-fill": "var(--accent)",
      "--ui-chrome-bg": "var(--text)",
      "--ui-chrome-text": "var(--ink-chrome-text)",
      "--ui-chrome-muted": "var(--ink-chrome-muted)",
      "--ui-chrome-line": "color-mix(in srgb, var(--paper) 35%, var(--text))",
      "--ui-header-bg": "var(--text)",
      "--ui-header-text": "var(--ink-chrome-text)",
      "--ui-header-muted": "var(--ink-chrome-muted)",
      "--ui-nav-selected": "var(--paper)",
      "--ui-nav-ink": "var(--text)",
      "--ui-nav-rule": "inset 4px 0 var(--accent)",
      "--ui-nav-radius": "var(--control-radius-small)",
      "--ui-tab-selected": "var(--accent)",
      "--ui-tab-rule": "inset 0 -3px var(--text)",
      "--ui-overlay-edge": "var(--text)",
      "--ui-overlay-rule": "inset 0 3px var(--accent)",
    }),
  },
  {
    id: "gridwork",
    name: "Gridwork",
    description:
      "Technical lattice, bracketed selection and calibrated controls",
    signatures: ["bracket-fields", "lattice-chrome", "calibrated-controls"],
    recipe: profile({
      "--control-radius": "calc(var(--radius) * 0.2)",
      "--control-radius-small": "calc(var(--radius) * 0.1)",
      "--panel-radius": "calc(var(--radius) * 0.35)",
      "--window-radius": "calc(var(--radius) * 0.4)",
      "--control-surface": "var(--paper)",
      "--control-edge": "var(--muted)",
      "--action-rule": "inset 3px 0 var(--line), inset -3px 0 var(--line)",
      "--field-surface": "var(--paper)",
      "--field-edge": "var(--line)",
      "--field-rule": "inset 3px 0 var(--muted), inset -3px 0 var(--muted)",
      "--field-focus-rule":
        "inset 3px 0 var(--focus), inset -3px 0 var(--focus), inset 0 0 0 1px var(--focus)",
      "--checkbox-radius": "0",
      "--switch-radius": "var(--control-radius-small)",
      "--switch-knob-radius": "0",
      "--slider-track-height": "2px",
      "--slider-thumb-width": "12px",
      "--slider-thumb-height": "16px",
      "--slider-thumb-radius": "0",
      "--ui-chrome-pattern":
        "linear-gradient(color-mix(in srgb, var(--line) 45%, transparent) 1px, transparent 1px), linear-gradient(90deg, color-mix(in srgb, var(--line) 45%, transparent) 1px, transparent 1px)",
      "--ui-chrome-pattern-size": "24px 24px",
      "--ui-nav-selected": "var(--paper)",
      "--ui-nav-rule": "inset 3px 0 var(--accent), inset -3px 0 var(--accent)",
      "--ui-nav-radius": "var(--control-radius-small)",
      "--ui-panel-rule": "inset 0 3px var(--line), inset 0 -1px var(--line)",
      "--ui-tab-selected": "var(--paper)",
      "--ui-tab-rule": "inset 3px 0 var(--accent), inset -3px 0 var(--accent)",
      "--ui-overlay-rule": "inset 3px 0 var(--line), inset -3px 0 var(--line)",
    }),
  },
  {
    id: "cutline",
    name: "Cutline",
    description: "Graphic edges, diagonal chrome accents and emphatic framing",
    signatures: ["graphic-fields", "hatched-chrome", "offset-framing"],
    recipe: profile({
      "--control-radius": "calc(var(--radius) * 0.3)",
      "--control-radius-small": "calc(var(--radius) * 0.15)",
      "--panel-radius": "calc(var(--radius) * 0.4)",
      "--window-radius": "calc(var(--radius) * 0.5)",
      "--control-surface": "var(--paper)",
      "--control-edge": "var(--text)",
      "--action-rule": "inset -3px -3px var(--line)",
      "--primary-edge": "var(--text)",
      "--primary-rule":
        "inset -3px -3px color-mix(in srgb, var(--on-accent) 45%, transparent)",
      "--field-surface": "var(--paper)",
      "--field-edge": "var(--text)",
      "--field-rule": "inset -3px -3px var(--line)",
      "--field-focus-rule":
        "inset -3px -3px var(--focus), inset 0 0 0 1px var(--focus)",
      "--field-adornment-edge": "var(--text)",
      "--checkbox-radius": "0",
      "--switch-radius": "var(--control-radius-small)",
      "--switch-knob-radius": "var(--control-radius-small)",
      "--slider-track-height": "5px",
      "--slider-thumb-width": "14px",
      "--slider-thumb-height": "14px",
      "--slider-thumb-radius": "0",
      "--slider-thumb-fill": "var(--accent)",
      "--ui-chrome-pattern":
        "repeating-linear-gradient(135deg, transparent, transparent 7px, color-mix(in srgb, var(--line) 35%, transparent) 7px, color-mix(in srgb, var(--line) 35%, transparent) 8px)",
      "--ui-nav-rule": "inset -3px -3px var(--accent)",
      "--ui-nav-radius": "var(--control-radius-small)",
      "--ui-panel-rule": "inset -3px -3px var(--line)",
      "--ui-tab-rule": "inset -3px -3px var(--accent)",
      "--ui-overlay-edge": "var(--text)",
      "--ui-overlay-rule": "inset -3px -3px var(--line)",
    }),
  },
];
export function interfaceStyleVariables(
  id: InterfaceStyleId,
): Record<string, string> {
  const style = interfaceStyles.find((item) => item.id === id);
  if (!style) throw new Error("Unknown interface style.");
  return { ...style.recipe };
}
