/** Additive resource-backed tools. No note content or file bytes are rewritten. */
export const researchToolsMigration = `
ALTER TABLE notes ADD COLUMN source_format text NOT NULL DEFAULT 'markdown' CHECK(source_format IN ('markdown','latex'));
CREATE TABLE tool_projects(resource_id uuid PRIMARY KEY REFERENCES resources ON DELETE CASCADE,kind text NOT NULL CHECK(kind IN ('math','image')),settings jsonb NOT NULL DEFAULT '{}',version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tool_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),resource_id uuid NOT NULL REFERENCES tool_projects ON DELETE CASCADE,author_id text NOT NULL REFERENCES "user",label text NOT NULL,source text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX tool_history_resource ON tool_history(resource_id,created_at DESC);
CREATE TABLE image_edit_leases(resource_id uuid PRIMARY KEY REFERENCES tool_projects ON DELETE CASCADE,owner_id text NOT NULL REFERENCES "user",token uuid NOT NULL,fence bigint NOT NULL DEFAULT 1,expires_at timestamptz NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tool_providers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),group_id uuid NOT NULL REFERENCES groups ON DELETE CASCADE,name text NOT NULL,kind text NOT NULL CHECK(kind IN ('private','openrouter')),endpoint text NOT NULL,model text NOT NULL,credential text NOT NULL,capabilities text[] NOT NULL DEFAULT '{math}',enabled boolean NOT NULL DEFAULT false,daily_limit integer NOT NULL DEFAULT 25 CHECK(daily_limit BETWEEN 1 AND 10000),version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tool_jobs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),resource_id uuid REFERENCES resources ON DELETE CASCADE,version_id uuid REFERENCES file_versions ON DELETE CASCADE,owner_id text NOT NULL REFERENCES "user",provider_id uuid REFERENCES tool_providers ON DELETE SET NULL,kind text NOT NULL CHECK(kind IN ('office-preview','ocr','generate','check','explain')),status text NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','running','complete','failed','cancelled','uncertain')),input jsonb NOT NULL DEFAULT '{}',result jsonb,error text,attempts integer NOT NULL DEFAULT 0,lease_until timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX tool_jobs_pending ON tool_jobs(status,created_at);
CREATE UNIQUE INDEX tool_office_preview_unique ON tool_jobs(version_id,kind) WHERE kind='office-preview' AND status IN ('queued','running','complete');
CREATE TABLE resource_comments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),resource_id uuid NOT NULL REFERENCES resources ON DELETE CASCADE,version_id uuid REFERENCES file_versions ON DELETE CASCADE,author_id text NOT NULL REFERENCES "user",body text NOT NULL CHECK(length(body) BETWEEN 1 AND 20000),anchor jsonb NOT NULL DEFAULT '{}',resolved boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX resource_comments_target ON resource_comments(resource_id,version_id,created_at);
`;
