import type { Palette } from "./appearance";

/** Compiled, reviewed packs only. Never construct an import from a saved ID. */
export const themePackIds = [
  "default",
  "paper-research",
  "technical-slate",
  "botanical",
  "spectrum",
  "graphite-ink",
] as const;
export type ThemePackId = (typeof themePackIds)[number];
export type ThemePackManifest = {
  format: "axiom-theme-pack";
  version: 1;
  id: Exclude<ThemePackId, "default">;
  name: string;
  description: string;
  author: string;
  license: string;
  minimumAppearanceSchema: number;
  css: string;
  assets: string[];
  fixtures: string[];
  palettes: { light: Palette; dark: Palette };
};
export const themePacks: readonly ThemePackManifest[] = [
  {
    format: "axiom-theme-pack",
    version: 1,
    id: "paper-research",
    name: "Paper Research",
    description:
      "Warm archival paper, precise ink, and understated research surfaces.",
    author: "Axiom contributors",
    license: "MIT",
    minimumAppearanceSchema: 5,
    css: "apps/web/themes/paper-research.css",
    assets: [],
    fixtures: ["docs/theme-fixtures/research.md"],
    palettes: {
      light: {
        bg: "#f5f2eb",
        paper: "#fffcf5",
        sidebar: "#eeeae0",
        surface: "#fffcf5",
        hover: "#e5dfd2",
        text: "#292722",
        muted: "#696357",
        subtle: "#71695d",
        line: "#c5bbab",
        accent: "#72512b",
        accentBg: "#eae0ce",
        onAccent: "#ffffff",
        selection: "#ded0b4",
        focus: "#765527",
        green: "#3d6944",
        warning: "#855817",
        danger: "#a73635",
        code: "#f0ebe1",
        codeText: "#363127",
        syntax: "#705171",
        callout: "#f2ecdf",
      },
      dark: {
        bg: "#191815",
        paper: "#22211d",
        sidebar: "#28261f",
        surface: "#2c2922",
        hover: "#383329",
        text: "#eee9dc",
        muted: "#c0b7a5",
        subtle: "#b8af9c",
        line: "#655d4d",
        accent: "#e0bd82",
        accentBg: "#403425",
        onAccent: "#292116",
        selection: "#54462f",
        focus: "#efd3a0",
        green: "#b4d29f",
        warning: "#edc78b",
        danger: "#f0aaa3",
        code: "#1b1a16",
        codeText: "#ece3d0",
        syntax: "#d3b8d1",
        callout: "#302a20",
      },
    },
  },
  {
    format: "axiom-theme-pack",
    version: 1,
    id: "technical-slate",
    name: "Technical Slate",
    description:
      "Cool mineral surfaces, blue annotations, and crisp technical contrast.",
    author: "Axiom contributors",
    license: "MIT",
    minimumAppearanceSchema: 5,
    css: "apps/web/themes/technical-slate.css",
    assets: [],
    fixtures: ["docs/theme-fixtures/research.md"],
    palettes: {
      light: {
        bg: "#eef2f6",
        paper: "#fbfdff",
        sidebar: "#e6ecf2",
        surface: "#f5f8fc",
        hover: "#dce5ee",
        text: "#202c3a",
        muted: "#526276",
        subtle: "#5b6b7c",
        line: "#b8c7d6",
        accent: "#245b8a",
        accentBg: "#dceaf6",
        onAccent: "#ffffff",
        selection: "#c5dcef",
        focus: "#1d5e94",
        green: "#28664f",
        warning: "#84551c",
        danger: "#a83443",
        code: "#e9eff6",
        codeText: "#23364a",
        syntax: "#635084",
        callout: "#e6eff8",
      },
      dark: {
        bg: "#111921",
        paper: "#18232e",
        sidebar: "#1d2b38",
        surface: "#22313e",
        hover: "#2d4050",
        text: "#e9f0f7",
        muted: "#b4c6d6",
        subtle: "#aabbcb",
        line: "#52697f",
        accent: "#a0c9f1",
        accentBg: "#28455e",
        onAccent: "#15293d",
        selection: "#3a5974",
        focus: "#b1d7fa",
        green: "#9dd6bf",
        warning: "#ebca94",
        danger: "#f5a9b6",
        code: "#131d28",
        codeText: "#e1edf9",
        syntax: "#c9b7ec",
        callout: "#203347",
      },
    },
  },
  {
    format: "axiom-theme-pack",
    version: 1,
    id: "botanical",
    name: "Botanical",
    description:
      "Warm mineral paper, forest annotations and gently inked research captions.",
    author: "Axiom contributors",
    license: "MIT",
    minimumAppearanceSchema: 12,
    css: "apps/web/themes/botanical.css",
    assets: [],
    fixtures: ["docs/theme-fixtures/research.md"],
    palettes: {
      light: {
        bg: "#f2f4ed",
        paper: "#fcfdf8",
        sidebar: "#e9eee2",
        surface: "#f0f4e9",
        hover: "#dce6d1",
        text: "#233528",
        muted: "#51624f",
        subtle: "#5c6a56",
        line: "#b8c7ad",
        accent: "#326243",
        accentBg: "#dfebda",
        onAccent: "#ffffff",
        selection: "#d2e4ca",
        focus: "#275836",
        green: "#326243",
        warning: "#805a20",
        danger: "#a4353c",
        code: "#eaf0e2",
        codeText: "#2a3c2b",
        syntax: "#705574",
        callout: "#e5eddb",
      },
      dark: {
        bg: "#161c18",
        paper: "#1d2620",
        sidebar: "#243029",
        surface: "#29352c",
        hover: "#37483b",
        text: "#e9efe3",
        muted: "#becdb5",
        subtle: "#b2c1a9",
        line: "#5b715d",
        accent: "#b4d4a2",
        accentBg: "#32482f",
        onAccent: "#20311c",
        selection: "#3e5838",
        focus: "#c1e3ae",
        green: "#b4d4a2",
        warning: "#e3c292",
        danger: "#efacaf",
        code: "#17211a",
        codeText: "#e4eddb",
        syntax: "#d9b7d5",
        callout: "#2a3828",
      },
    },
  },
  {
    format: "axiom-theme-pack",
    version: 1,
    id: "spectrum",
    name: "Spectrum",
    description:
      "Cool violet ink, crystalline surfaces and expressive but readable references.",
    author: "Axiom contributors",
    license: "MIT",
    minimumAppearanceSchema: 12,
    css: "apps/web/themes/spectrum.css",
    assets: [],
    fixtures: ["docs/theme-fixtures/research.md"],
    palettes: {
      light: {
        bg: "#f2eff8",
        paper: "#fefcff",
        sidebar: "#ebe5f5",
        surface: "#f4effb",
        hover: "#e3d9f1",
        text: "#302b43",
        muted: "#655977",
        subtle: "#6f627f",
        line: "#c5b8d8",
        accent: "#70449a",
        accentBg: "#eadcf7",
        onAccent: "#ffffff",
        selection: "#dfcdf3",
        focus: "#6a358f",
        green: "#366650",
        warning: "#845220",
        danger: "#a43459",
        code: "#eeebf6",
        codeText: "#392e4a",
        syntax: "#7a438e",
        callout: "#eee3f8",
      },
      dark: {
        bg: "#191621",
        paper: "#24202f",
        sidebar: "#2c263a",
        surface: "#332c42",
        hover: "#443854",
        text: "#f0e9fa",
        muted: "#c8b9dc",
        subtle: "#bcadd0",
        line: "#75608c",
        accent: "#d0acf6",
        accentBg: "#49305f",
        onAccent: "#2e1b41",
        selection: "#563e6e",
        focus: "#debdff",
        green: "#a5d8bb",
        warning: "#ebc390",
        danger: "#f3adc8",
        code: "#1c1726",
        codeText: "#e8dcf7",
        syntax: "#dfb7ec",
        callout: "#382741",
      },
    },
  },
  {
    format: "axiom-theme-pack",
    version: 1,
    id: "graphite-ink",
    name: "Graphite Ink",
    description:
      "Neutral drafting paper, graphite annotations and restrained technical rules.",
    author: "Axiom contributors",
    license: "MIT",
    minimumAppearanceSchema: 12,
    css: "apps/web/themes/graphite-ink.css",
    assets: [],
    fixtures: ["docs/theme-fixtures/research.md"],
    palettes: {
      light: {
        bg: "#efefed",
        paper: "#fdfdfb",
        sidebar: "#e5e6e3",
        surface: "#f1f1ee",
        hover: "#dedfda",
        text: "#272b2b",
        muted: "#585e5d",
        subtle: "#646966",
        line: "#bfc3bd",
        accent: "#455b62",
        accentBg: "#dee7e8",
        onAccent: "#ffffff",
        selection: "#d2dedf",
        focus: "#344c54",
        green: "#3b6550",
        warning: "#80541e",
        danger: "#a4383f",
        code: "#e9eae7",
        codeText: "#303735",
        syntax: "#675471",
        callout: "#e5eae7",
      },
      dark: {
        bg: "#181b1b",
        paper: "#222626",
        sidebar: "#2a2f2f",
        surface: "#303636",
        hover: "#404848",
        text: "#e9eded",
        muted: "#bdc7c5",
        subtle: "#b2bfba",
        line: "#65726f",
        accent: "#b8d3d6",
        accentBg: "#364a4d",
        onAccent: "#1d3235",
        selection: "#455e61",
        focus: "#c6e2e4",
        green: "#abd3bd",
        warning: "#e3c598",
        danger: "#efafb5",
        code: "#1a1f1e",
        codeText: "#e1e9e5",
        syntax: "#ceb8d7",
        callout: "#2b3834",
      },
    },
  },
];
export function themePack(id: string) {
  return themePacks.find((pack) => pack.id === id);
}
